### PR TITLE
Add checkbox instructor form

### LINKED ISSUE #15: Add search by lecture instructor checkbox to search by instructor form
- [x] Map the professor into an array of last name then first name.
- [x] Change BasicCourseSearchForm.js to have professors to search for
- [ ] Incorporate the backend and frontend together
- [ ] npx stryker for mutation test
- [x] mvn test for backend test
- [x] npm test for frontend test

### PR DESCRIPTION
**Pull request by JNewman-cell**
Description: Added checkbox to the search by instructor form that adds the functionality of choosing Lectures only to the results of the courses.

Storybook entry: https://ucsb-cs156-s23.github.io/proj-courses-s23-7pm-2/prs/31/storybook/?path=/docs/components-basiccoursesearch-coursebyinstructorsearch--default
image

### CODE REVIEW

**Review by justinthecao — DISMISSED** [review]
Looks good to me, swagger works and checkbox appears on storybook

**Review by pconrad — APPROVED** [review]
LGTM!  Will test on staff-qa

**Review by pconrad — CHANGES_REQUESTED** [review]
I'm confused about this PR.  It has both frontend and backend functionality in it, but the two don't seem to be connected.   That is:
* There's a form and a storybook element.
* There's a backend endpoint modification

But there doesn't seem to be any page in the app where this frontend component is used, or this backend endpoint is used.

Am I missing something?

If not, then:

* This needs to be much more clearly spelled out in the PR description.   Reviewers in industry will not be happy if you give them a PR like this and make them do all the work to figure out what's going on.
* Second: you should either break up your PRs into small testable single units or code, OR you should deliver an entire vertical slice of end user functionality.

Unless I'm missing something, this does neither.  It's a front end piece, and a backend piece, each of which has to be tested separately.  It took me way too long to figure that out.  (And indeed, I'm still not even sure I'm right... and that's not good.

**Review by justinthecao — APPROVED** [review]
checkbox works on swagger and the page itself. Lgtm

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
