### PR TITLE
Change search by instructor query to be case insensitive

### PR DESCRIPTION
**Pull request by Arik**
By request of @NateHoang. The alternative is having a headache of logic in the page/form, especially when factoring in autocomplete.

### CODE REVIEW

**Review by pconrad — APPROVED** [review]
LGTM... will test on QA before merging

**Comment by justinthecao** [comment]
looks good, swagger works with lower case

**Review by justinthecao — APPROVED** [review]
Looks good to me, swagger works with lowercase

**Comment by Arik** [comment]
Obsolete - the query and controller will be revamped in a future PR.

**Pull request closed without merging**
